services:
  - type: web
    name: recipe-recommendation-api
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend 'app:app'
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: backend

  - type: web
    name: recipe-recommendation-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: recipe-recommendation-api
          envVarKey: RENDER_EXTERNAL_URL 