services:
  - type: web
    name: recipe-recommendation-api
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: .

  - type: web
    name: recipe-recommendation-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: recipe-recommendation-api
          envVarKey: RENDER_EXTERNAL_URL 